name:                web3
version:             0.9.1.0
synopsis:            Web3 API for Haskell.
description:         Client library for Third Generation of Web.
github:              "airalab/hs-web3"
license:             BSD-3-Clause
license-file:        LICENSE
author:              Alexander Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Alexander Krupenkin 2016"
category:            Network

extra-source-files:
- README.md
- CHANGELOG.md
- stack.yaml
- examples/token/ERC20.hs
- examples/token/ERC20.json
- examples/token/Main.hs
- examples/token/stack.yaml
- examples/token/package.yaml
- examples/polkadot/Main.hs
- examples/polkadot/stack.yaml
- examples/polkadot/package.yaml
- examples/scale/Main.hs
- examples/scale/stack.yaml
- examples/scale/package.yaml
- test/contracts/Registry.json
- test/contracts/SimpleStorage.json
- test/contracts/ComplexStorage.json
- test/contracts/Linearization.json

dependencies:
- base                 >4.11      && <4.14
- template-haskell     >=2.12     && <2.16
- http-client-tls      >=0.3.5.1  && <0.4
- microlens-aeson      >=2.2.0.2  && <2.4
- microlens-mtl        >=0.1.11.0 && <0.3
- microlens-th         >=0.4.1.1  && <0.5
- microlens            >=0.4.8.1  && <0.5
- data-default         >=0.7.1.1  && <0.8
- generics-sop         >=0.3.1.0  && <0.6
- transformers         >=0.5.2.0  && <0.6
- http-client          >=0.5.7.1  && <0.7
- uuid-types           >=1.0.3    && <1.1
- bytestring           >=0.10.8.1 && <0.11
- cryptonite           >=0.23     && <0.28
- exceptions           >=0.8.3    && <0.11
- bitvec               >=1.0.0    && <2.0
- vector               >=0.12     && <0.13
- basement             >=0.0.4    && <0.1
- machines             >=0.6.3    && <0.8
- OneTuple             >=0.2.1    && <0.3
- relapse              >=1.0.0.0  && <2.0
- tagged               >=0.8.5    && <0.9
- parsec               >=3.1.11   && <3.2
- memory               >=0.14.11  && <0.16
- cereal               >=0.5.4.0  && <0.6
- aeson                >=1.2.2.0  && <1.5
- vinyl                >=0.5.3    && <0.14
- async                >=2.1.1.1  && <2.3
- text                 >=1.2.2.2  && <1.3
- mtl                  >=2.2.1    && <2.3
- websockets           >=0.11     && <0.13
- network              >=2.6      && <3.2
- servant-client       >=0.13     && <0.17
- servant              >=0.13     && <0.17
- http-media           >=0.7      && <0.8.1
- errors               >=2.2      && <2.4
- hspec                >=2.4      && <2.8
- base58string         >=0.10.0   && <0.11
- tar                  >=0.5      && <0.6  
- unordered-containers >=0.2      && <0.3 
- http-types           >=0.12     && <0.14 
- attoparsec           >=0.13.2.1 && <0.14 

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

flags:
  debug:
    description: Enable debug compiler options
    default: False
    manual: True

  compiler:
    description: Enable Solidity compiler
    default: False
    manual: True

when:
- condition: flag(debug)
  ghc-options:      -ddump-splices

- condition: flag(compiler)
  source-dirs:      compiler
  cpp-options:      -DSOLIDITY_COMPILER
  dependencies:     containers
  extra-libraries:  solidity
  c-sources:        ./compiler/cbits/solidity_lite.cpp
  include-dirs:     ./compiler/cbits

library:
  source-dirs: src

tests:
  unit:
    main:             Spec.hs
    source-dirs:
    - unit
    - src
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.4  && <2.8
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.4  && <2.8
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  live:
    main:             Spec.hs
    source-dirs:
    - test
    - src
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.4  && <2.8
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.4  && <2.8
    - split                >=0.2.3  && <0.3
    - random               >=1.1    && <1.2
    - time                 >=1.6.0  && <1.11
    - stm                  >=2.4.4  && <2.6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
